import type { ClashConfig, ProxyGroup } from "./types";

const REGION_NAMES = ["HK", "TW", "JP", "SG", "KR", "US", "CA", "UK", "EU", "AU", "AS"];
const BUILTIN_PROXY_NAMES = new Set(["DIRECT", "REJECT", "REJECT-DROP", "PASS", "COMPATIBLE"]);

/** All names generated by the four variants, plus Mihomo's built-in targets. */
export const RESERVED_GROUP_NAMES = new Set([
  "main", "All", "GLOBAL", "AI", "Google", "YouTube", "GitHub", "Netflix",
  "TikTok", "Telegram", "Steam", "Apple", "Microsoft", "Spotify", "广告拦截",
  "Other", "info", "全部", "自动测速", "AI 自动测速", "Telegram - Fallback",
  ...REGION_NAMES,
  ...["All", "AI", "Other", ...REGION_NAMES].map((name) => `URL Test - ${name}`),
  ...BUILTIN_PROXY_NAMES,
]);

export const isReservedProxyName = (name: string): boolean =>
  [...RESERVED_GROUP_NAMES].some((reserved) => reserved.toLowerCase() === name.toLowerCase());

const escapeRegex = (value: string): string =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * filter applies to include-all/provider nodes, not explicit group references.
 * exclude-filter would also remove the explicitly referenced URL Test groups.
 * Provider names are checked after their own overrides; no payload snapshot is needed.
 */
export const guardProviderNames = (groups: ProxyGroup[]): ProxyGroup[] => {
  const reserved = [...RESERVED_GROUP_NAMES].map(escapeRegex).join("|");
  return groups.map((group) => {
    if (!group["include-all"]) return group;
    const include = String(group.filter || "").replace(/^\(\?i\)/, "");
    return {
      ...group,
      filter: `(?i)^(?!(?:${reserved})$)${include ? `(?=[\\s\\S]*(?:${include}))` : ""}[\\s\\S]*$`,
    };
  });
};

/** Follow renamed inline nodes in supported node/provider dialer references. */
export const rewriteProxyReferences = (
  config: ClashConfig,
  renamed: Map<string, string>,
): void => {
  const rewrite = (record: Record<string, any>, key: string) => {
    // An invalid subscription node named DIRECT cannot take ownership of the built-in.
    if (typeof record[key] === "string" && !BUILTIN_PROXY_NAMES.has(record[key]) && renamed.has(record[key]))
      record[key] = renamed.get(record[key]);
  };
  for (const proxy of Array.isArray(config.proxies) ? config.proxies : [])
    if (proxy && typeof proxy === "object") rewrite(proxy, "dialer-proxy");
  for (const section of ["proxy-providers", "rule-providers"]) {
    for (const provider of Object.values(config[section] || {}) as Record<string, any>[]) {
      if (!provider || typeof provider !== "object") continue;
      rewrite(provider, "proxy");
      rewrite(provider, "dialer-proxy");
      if (provider.override && typeof provider.override === "object")
        rewrite(provider.override, "dialer-proxy");
    }
  }
};
